Max Enrollments Number
ndunand/moodle-mod_choicegroup pull request #154
Opened 2021-07-14 18:51 UTC by sameer-ah

Fix: #142
-If 'Allow enrollment to multiple groups' is selected, there is an extra field to provide max enrollments number. Use default value 0 if there is no limit.

2021-07-15 15:59 UTC, ndunand requested changes
Thanks for sharing your work on this!

Just 2 small comments that I'd ask you to consider.

2021-07-15 15:59 UTC, ndunand commented on view.php
> +$maxenrollments     = optional_param('maxenrollments', '', PARAM_INT);
Do we need this optional_param here? More simply, we could simply use `$choicegroup->maxenrollments` throughout the code.

2021-07-15 15:59 UTC, ndunand commented on view.php
> +                    array('id' => $cm->id, 'notify' => 'mustchoosemax', 'sesskey' => sesskey(), 'maxenrollments' => $maxenrollments)));
... so we can remove the redundant `maxenrollments ` redirect param here.

2021-07-15 16:51 UTC, sameer-ah commented
Thanks for the review feedback. I have made suggested changes.

2021-07-16 06:31 UTC, merged

2021-07-16 06:32 UTC, ndunand commented
Thanks @sameer-ah for providing this feature! This will be released asap.